version: "3"
services:
  appdb:
    image: postgres:latest
    container_name: "appdb"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_DB=test01
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local